// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDaNmL9HK1x0jq2YYDgpBEHWCctdaO7Y',
    appId: '1:299269440224:web:93fa1117082fa10b2d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    authDomain: 'bancolombia-fake.firebaseapp.com',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    measurementId: 'G-H5D2LD83PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwOaML8Tt9AWD_aAcVm6u3LZZ_fmPDaU',
    appId: '1:299269440224:android:1c59a5cfc1eb2fa62d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjZKa94_DhLOCPSd1DAtjY5Wvt4uYV4CI',
    appId: '1:299269440224:ios:4d06305acc86ab312d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    iosBundleId: 'com.example.bancolombiaV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjZKa94_DhLOCPSd1DAtjY5Wvt4uYV4CI',
    appId: '1:299269440224:ios:4d06305acc86ab312d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    iosBundleId: 'com.example.bancolombiaV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDaNmL9HK1x0jq2YYDgpBEHWCctdaO7Y',
    appId: '1:299269440224:web:175eae4272f9a7892d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    authDomain: 'bancolombia-fake.firebaseapp.com',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    measurementId: 'G-6X7VWLGBV4',
  );
}
